version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: monthly
    day: wednesday
    time: '15:00'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
    day: wednesday
    time: '15:00'
  groups:
    github-actions:
      patterns:
      - '*'
