version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: /
  schedule:
    cron: 0 16 12 * *
  groups:
    github-actions:
      patterns:
      - '*'
